name: Test CI

on:
  workflow_dispatch: # Note: Visual regression tests require a PR or Commit
  push:
  pull_request:

jobs:

  test_all:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ${{ matrix.os }} General Tests - Headless
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew testAll

      - name: Run ${{ matrix.os }} Regression Tests - Headless
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew regressionTest

      - name: Generate ${{ matrix.os }} JUnit Test Reports
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: ${{ matrix.os }} Tests
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit

      - name: Generate ${{ matrix.os }} Regression Test Reports
        if: success() || failure()
        uses: reg-viz/reg-actions@v2
        with:
          github-token: "${{ secrets.ACCESS_TOKEN }}"
          image-directory-path: "./tests/images/"
          artifact-name: "reg-${{ matrix.os }}"

